export const themes = {
  default: {
    name: "Classico",
    background: "bg-gradient-to-br from-slate-50 to-blue-50",
    cardBg: "bg-white",
    accent: "#0066FF",
    accentLight: "#E8F0FE",
    text: "text-slate-900",
    textMuted: "text-slate-500",
    border: "border-slate-200",
    css: {
      "--accent": "#0066FF",
      "--accent-light": "#E8F0FE",
      "--bg-from": "#f8fafc",
      "--bg-to": "#eff6ff",
    },
  },
  ocean: {
    name: "Oceano",
    background: "bg-gradient-to-br from-cyan-50 to-blue-100",
    cardBg: "bg-white/90 backdrop-blur-sm",
    accent: "#0891B2",
    accentLight: "#E0F7FA",
    text: "text-cyan-900",
    textMuted: "text-cyan-600",
    border: "border-cyan-200",
    css: {
      "--accent": "#0891B2",
      "--accent-light": "#E0F7FA",
      "--bg-from": "#ecfeff",
      "--bg-to": "#dbeafe",
    },
  },
  sunset: {
    name: "Tramonto",
    background: "bg-gradient-to-br from-orange-50 to-rose-100",
    cardBg: "bg-white/90 backdrop-blur-sm",
    accent: "#EA580C",
    accentLight: "#FFF7ED",
    text: "text-orange-900",
    textMuted: "text-orange-600",
    border: "border-orange-200",
    css: {
      "--accent": "#EA580C",
      "--accent-light": "#FFF7ED",
      "--bg-from": "#fff7ed",
      "--bg-to": "#ffe4e6",
    },
  },
  forest: {
    name: "Foresta",
    background: "bg-gradient-to-br from-emerald-50 to-green-100",
    cardBg: "bg-white/90 backdrop-blur-sm",
    accent: "#059669",
    accentLight: "#ECFDF5",
    text: "text-emerald-900",
    textMuted: "text-emerald-600",
    border: "border-emerald-200",
    css: {
      "--accent": "#059669",
      "--accent-light": "#ECFDF5",
      "--bg-from": "#ecfdf5",
      "--bg-to": "#dcfce7",
    },
  },
  midnight: {
    name: "Notte",
    background: "bg-gradient-to-br from-slate-900 to-indigo-950",
    cardBg: "bg-slate-800/90 backdrop-blur-sm",
    accent: "#818CF8",
    accentLight: "#1E1B4B",
    text: "text-white",
    textMuted: "text-slate-400",
    border: "border-slate-700",
    css: {
      "--accent": "#818CF8",
      "--accent-light": "#1E1B4B",
      "--bg-from": "#0f172a",
      "--bg-to": "#1e1b4b",
    },
  },
  energia: {
    name: "Energia DDG",
    background: "bg-gradient-to-br from-sky-50 to-cyan-100",
    cardBg: "bg-white/95 backdrop-blur-sm",
    accent: "#0284C7",
    accentLight: "#E0F2FE",
    text: "text-sky-900",
    textMuted: "text-sky-600",
    border: "border-sky-200",
    css: {
      "--accent": "#0284C7",
      "--accent-light": "#E0F2FE",
      "--bg-from": "#f0f9ff",
      "--bg-to": "#cffafe",
    },
  },
} as const;

export type ThemeKey = keyof typeof themes;
